apiVersion: batch/v1
kind: Job
metadata:
  name: workflowop-1
spec:
  template:
    spec:
      serviceAccount: workflowop
      serviceAccountName: workflowop
      containers:
      - name: workflowop
        image: workflowop:1546
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /data
          name: data
        env:
          - name: SPEC
            value: /data/spec.json
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: /mount-9p
