apiVersion: batch/v1
kind: Job
metadata:
  name: workflowop-1
spec:
  template:
    spec:
      serviceAccount: workflowop
      serviceAccountName: workflowop
      containers:
      - name: workflowop
        image: workflowop
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /spec
            name: spec
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: /tmp
      - name: spec
        configMap:
          name: workflowop-spec1
